db:
  url: jdbc:mysql://localhost:3306/hr-app
  username: root
  password: password123

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: @mailUsername
    password: @mailPassword
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




