db:
  url: jdbc:mysql://localhost:3306/hr-app
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:password123}

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: 'baioretto66@gmail.com'
    password: 'bzoz sibf ztcd qsyh'
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




